# Fake pinout for FFG901 package

# Bank 18
set_property PACKAGE_PIN F30 [get_ports io_mainClk]

# Bank 18
set_property PACKAGE_PIN G30 [get_ports io_uart_txd]
set_property PACKAGE_PIN H30 [get_ports io_uart_rxd]

# Bank 18
set_property PACKAGE_PIN A14 [get_ports sw[0]]
set_property PACKAGE_PIN A15 [get_ports sw[1]]
set_property PACKAGE_PIN A16 [get_ports sw[2]]
set_property PACKAGE_PIN A17 [get_ports sw[3]]
set_property PACKAGE_PIN B14 [get_ports sw[4]]
set_property PACKAGE_PIN B15 [get_ports sw[5]]
set_property PACKAGE_PIN B17 [get_ports sw[6]]
set_property PACKAGE_PIN C14 [get_ports sw[7]]
set_property PACKAGE_PIN C15 [get_ports sw[8]]
set_property PACKAGE_PIN C16 [get_ports sw[9]]
set_property PACKAGE_PIN C17 [get_ports sw[10]]
set_property PACKAGE_PIN D14 [get_ports sw[11]]
set_property PACKAGE_PIN D16 [get_ports sw[12]]
set_property PACKAGE_PIN D17 [get_ports sw[13]]
set_property PACKAGE_PIN E14 [get_ports sw[14]]
set_property PACKAGE_PIN E15 [get_ports sw[15]]

# Bank 17
set_property PACKAGE_PIN A25 [get_ports io_led[0]]
set_property PACKAGE_PIN A26 [get_ports io_led[1]]
set_property PACKAGE_PIN A27 [get_ports io_led[2]]
set_property PACKAGE_PIN A28 [get_ports io_led[3]]
set_property PACKAGE_PIN A30 [get_ports io_led[4]]
set_property PACKAGE_PIN B24 [get_ports io_led[5]]
set_property PACKAGE_PIN B25 [get_ports io_led[6]]
set_property PACKAGE_PIN B27 [get_ports io_led[7]]
set_property PACKAGE_PIN B28 [get_ports io_led[8]]
set_property PACKAGE_PIN B29 [get_ports io_led[9]]
set_property PACKAGE_PIN B30 [get_ports io_led[10]]
set_property PACKAGE_PIN C24 [get_ports io_led[11]]
set_property PACKAGE_PIN C25 [get_ports io_led[12]]
set_property PACKAGE_PIN C26 [get_ports io_led[13]]
set_property PACKAGE_PIN C27 [get_ports io_led[14]]
set_property PACKAGE_PIN C29 [get_ports io_led[15]]


set_property IOSTANDARD LVCMOS33 [get_ports io_mainClk]

set_property IOSTANDARD LVCMOS33 [get_ports io_uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports io_uart_rxd]

set_property IOSTANDARD LVCMOS33 [get_ports sw[0]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[1]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[2]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[3]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[4]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[5]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[6]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[7]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[8]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[9]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[10]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[11]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[12]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[13]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[14]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[15]]

set_property IOSTANDARD LVCMOS33 [get_ports io_led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[4]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[5]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[6]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[7]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[8]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[9]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[10]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[11]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[12]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[13]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[14]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[15]]
