# Fake pinout for FFG1926 package

# Bank 34
set_property PACKAGE_PIN V15 [get_ports io_mainClk]

# Bank 34
set_property PACKAGE_PIN U15 [get_ports io_uart_txd]
set_property PACKAGE_PIN U16 [get_ports io_uart_rxd]

# Bank 34
set_property PACKAGE_PIN A13 [get_ports sw[0]]
set_property PACKAGE_PIN A14 [get_ports sw[1]]
set_property PACKAGE_PIN A15 [get_ports sw[2]]
set_property PACKAGE_PIN A16 [get_ports sw[3]]
set_property PACKAGE_PIN B12 [get_ports sw[4]]
set_property PACKAGE_PIN B13 [get_ports sw[5]]
set_property PACKAGE_PIN B15 [get_ports sw[6]]
set_property PACKAGE_PIN B16 [get_ports sw[7]]
set_property PACKAGE_PIN C12 [get_ports sw[8]]
set_property PACKAGE_PIN C13 [get_ports sw[9]]
set_property PACKAGE_PIN C14 [get_ports sw[10]]
set_property PACKAGE_PIN C15 [get_ports sw[11]]
set_property PACKAGE_PIN D14 [get_ports sw[12]]
set_property PACKAGE_PIN D15 [get_ports sw[13]]
set_property PACKAGE_PIN E13 [get_ports sw[14]]
set_property PACKAGE_PIN E14 [get_ports sw[15]]

# Bank 36
set_property PACKAGE_PIN A8  [get_ports io_led[0]]
set_property PACKAGE_PIN A9  [get_ports io_led[1]]
set_property PACKAGE_PIN A10 [get_ports io_led[2]]
set_property PACKAGE_PIN A11 [get_ports io_led[3]]
set_property PACKAGE_PIN B8  [get_ports io_led[4]]
set_property PACKAGE_PIN B10 [get_ports io_led[5]]
set_property PACKAGE_PIN B11 [get_ports io_led[6]]
set_property PACKAGE_PIN C10 [get_ports io_led[7]]
set_property PACKAGE_PIN D10 [get_ports io_led[8]]
set_property PACKAGE_PIN D11 [get_ports io_led[9]]
set_property PACKAGE_PIN D12 [get_ports io_led[10]]
set_property PACKAGE_PIN E11 [get_ports io_led[11]]
set_property PACKAGE_PIN E12 [get_ports io_led[12]]
set_property PACKAGE_PIN F10 [get_ports io_led[13]]
set_property PACKAGE_PIN F11 [get_ports io_led[14]]
set_property PACKAGE_PIN G10 [get_ports io_led[15]]


set_property IOSTANDARD LVCMOS33 [get_ports io_mainClk]

set_property IOSTANDARD LVCMOS33 [get_ports io_uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports io_uart_rxd]

set_property IOSTANDARD LVCMOS33 [get_ports sw[0]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[1]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[2]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[3]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[4]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[5]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[6]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[7]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[8]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[9]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[10]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[11]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[12]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[13]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[14]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[15]]

set_property IOSTANDARD LVCMOS33 [get_ports io_led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[4]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[5]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[6]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[7]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[8]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[9]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[10]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[11]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[12]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[13]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[14]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led[15]]
