set_property PACKAGE_PIN A1 [get_ports i[0]]
set_property PACKAGE_PIN A2 [get_ports i[1]]
set_property PACKAGE_PIN A3 [get_ports i[2]]
set_property PACKAGE_PIN A4 [get_ports i[3]]
set_property PACKAGE_PIN A5 [get_ports o[0]]
set_property PACKAGE_PIN A6 [get_ports o[1]]
set_property PACKAGE_PIN A7 [get_ports o[2]]
set_property PACKAGE_PIN A8 [get_ports o[3]]
