set_property PACKAGE_PIN I_0 [get_ports i[0]]
set_property PACKAGE_PIN I_1 [get_ports i[1]]
set_property PACKAGE_PIN I_2 [get_ports i[2]]
set_property PACKAGE_PIN I_3 [get_ports i[3]]
set_property PACKAGE_PIN I_4 [get_ports i[4]]
set_property PACKAGE_PIN O_0 [get_ports o[0]]
set_property PACKAGE_PIN O_1 [get_ports o[1]]
set_property PACKAGE_PIN O_2 [get_ports o[2]]
