set_property PACKAGE_PIN A1 [get_ports i[0]]
set_property PACKAGE_PIN A2 [get_ports i[1]]
set_property PACKAGE_PIN A3 [get_ports i[2]]
set_property PACKAGE_PIN A4 [get_ports i[3]]
set_property PACKAGE_PIN A5 [get_ports i[4]]
set_property PACKAGE_PIN B1 [get_ports o[0]]
set_property PACKAGE_PIN B2 [get_ports o[1]]
set_property PACKAGE_PIN B3 [get_ports o[2]]
