set_property PACKAGE_PIN IO_1 [get_ports i[0]]
set_property PACKAGE_PIN IO_2 [get_ports i[1]]
set_property PACKAGE_PIN IO_3 [get_ports i[2]]
set_property PACKAGE_PIN IO_4 [get_ports i[3]]
set_property PACKAGE_PIN IO_5 [get_ports i[4]]
set_property PACKAGE_PIN IO_6 [get_ports o[0]]
set_property PACKAGE_PIN IO_7 [get_ports o[1]]
set_property PACKAGE_PIN IO_8 [get_ports o[2]]
